### ISSUE TITLE
Live stats do not work properly, match page doesn't show names

### ISSUE THREAD

**Issue by fanesahera** [PhlexPlexico/G5V#172] opened 2022-12-08 19:51 UTC
Hello,

Sorry, I am new to this.
I am not sure if this is a G5V issue or G5API issue I am facing.
The live stats won't update most of the time and sometimes if I refresh the website again and again, the team names also go from the match page as if it is failing to load - resulting in just 0 - 0 and rest of the information being blank.

I am not sure how to check G5API/G5V logs, can you help me figure that out?

**Comment by PhlexPlexico** [comment] 2022-12-08 22:50
Hi,

Are you running via docker, or just through the host machine?

**Comment by fanesahera** [comment] 2022-12-09 05:09
Thanks for the reply!
I am running manually through yarn and using NGINX as a reverse proxy.

**Comment by PhlexPlexico** [comment] 2022-12-09 12:51
Okay so a few things then.

- Ensure the API is running. This can be done by running `yarn pm2 logs G5API`. This will show if the API crashed or not.
- what's your nginx config look like for the reverse proxy? Are you able to access it through the URL? Such as `https://myget5.com/api/matches`?

I'm going to hazard a guess it's going to do with the reverse proxy setup, since that's usually the most finicky. you can find a working example config in the wiki of this repo :)

Thanks!

**Comment by fanesahera** [comment] 2022-12-09 13:38
![image](https://user-images.githubusercontent.com/120134745/206714375-4aee7e72-0843-4569-98d5-5288911fa189.png)

Thank you for your reply!
According to the logs, these HTTP requests take time and gets loaded after some time.
When I try to host many servers/matches at once, it bugs out.

Is it normal for the live stats to show after 5-20 seconds sometimes?

**Comment by fanesahera** [comment] 2022-12-09 13:41
![image](https://user-images.githubusercontent.com/120134745/206715032-2724ba66-e384-4e99-b9f9-0e43074f9538.png)
Thank you for your reply!

These Valve/Steam HTTP Client 1.0 requests take 15-20s to show. I believe when I try to host let's say, 4 matches at the same time, it bugs out because the previous requests are not completed yet.

**Comment by PhlexPlexico** [comment] 2022-12-09 13:44
I mean, that should be inconsequential. The updates will only show on round end, as per when the plugin sends the requests.

Does everything else work when you are viewing non-live matches? Like, does all the data on the site load properly?

**Comment by fanesahera** [comment] 2022-12-09 13:49
Yes. When the panel bugs out for example, I can use every other feature such as teams, seasons, servers etc. I will need to recheck the logs when it bugs out to find and provide more information.

**Comment by fanesahera** [comment] 2022-12-10 09:11
Hello,

I noticed the G5API is working perfectly. Right now, when the score is updated at the end of round, just the front end doesn't get updated. It shows this even after multiple rounds end. Should I send you the nginx config file?
![image](https://user-images.githubusercontent.com/120134745/206842651-72478aef-16a2-488e-9356-76688b9647ad.png)

**Comment by PhlexPlexico** [comment] 2022-12-11 05:42
I think that's because the front end checks if the match is currently started or not. If you idle on the page before the match has any values (I.e. everything in map stats table doesn't exist) it won't auto update. This is by design to ensure that ther a not too many open connections to the sockets at any given time, as there's no other way to determine if a match is running, or a match is stuck at the warmup (it happens quite a bit with the public pane).

**Comment by fanesahera** [comment] 2022-12-11 07:20
This happens after the match has started however.

**Comment by PhlexPlexico** [comment] 2022-12-15 13:47
Are you on the page before the match starts? And expecting the data to just flow in whenever the match begins? If you take a peep in the code, you will see that the event streams are only opened if it can find data for each route, and the end time of the match is null. Otherwise it will bring you to a static route (to save on some resources). Once a match is actually started, and there is some data (when a round ends, the player stats are updated), it should update the data automatically.

Thanks!

**Comment by PhlexPlexico** [comment] 2023-06-16 20:05
Closing this as there has not been activity in 6 months.

**Closed by PhlexPlexico** 2023-06-16 20:05 UTC
Labels: unverified bug
